AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 60
Metrics/BlockLength:
  Max: 1000
